- name: configure cart 
  hosts: cart
  become: yes
  tasks:
  - name: module disable
    ansible.builtin.command: dnf module disable nodejs -y

  - name: module enable
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: yes
      home: /app

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory


  - name: download cart code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
      dest: /tmp/cart.zip
      

  - name: Extract foo.tgz into /var/lib/foo
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes
      

  - name: Install npm
    community.general.npm:
      name: npm
      path: /app

  - name: Copy cart service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable is cart service
    ansible.builtin.service:
      name: cart
      state: started
      enabled: yes



