- name: configure redis
  hosts: redis
  become: yes
  tasks:
  - name: module disable
    ansible.builtin.command: dnf module disable redis -y

  - name: module enable
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: install redis
    ansible.builtin.dnf:
      name: redis
      state: present

  - name: Replace redis configure
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: disable protected mode
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: protected-mode no

  - name: start and enable redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes