 - name: configure shipping
   hosts: shipping
   become: yes
   tasks:
   - name: install maven
     ansible.builtin.dnf:
       name: maven
       state: installed

   - name: system user
     ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app

   - name: Create a directory 
     ansible.builtin.file:
       path: /app
       state: directory

   - name: download the shipping
     ansible.builtin.uri:
       url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
       dest: /tmp/shipping.zip

   - name: Unarchive a file that is already on the remote machine
     ansible.builtin.unarchive:
       src: /tmp/shipping.zip
       dest: /app
       remote_src: yes

   - name: Install maven
     ansible.builtin.package:
       name: maven
       state: installed

   - name: rename jar file
     ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
     args:
       chdir: /app

   - name: Copy Shipping Service
     ansible.builtin.copy:
       src: shipping.service
       dest: /etc/systemd/system/shipping.service
   
   - name: systemctl daemon-reload
     ansible.builtin.systemd_service:
      daemon_reload: true

   - name: start and enable user
     ansible.builtin.service:
       name: user
       state: started
       enabled: yes

   - name: import data
     community.mysql.mysql_db:
       name: all
       login_user: root
       login_password: RoboShop@1
       login_host: mysql.daws84s.site
       state: import
       target: "{{ item }}"
     loop:
     - /app/db/schema.sql
     - /app/db/app-user.sql
     - /app/db/master-data.sql

   - name: restart shipping
     ansible.builtin.service:
       state: restarted
       name: shipping



    