 - name: configure shipping
   hosts: shipping
   become: yes
   tasks:
   - name: install maven
     ansible.builtin.dnf:
       name: maven
       state: installed

   - name: system user
     ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app

   - name: Create a directory 
     ansible.builtin.file:
       path: /app
       state: directory

   - name: Download the shipping
     ansible.builtin.uri:
       url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
       src: /tmp/shipping.zip

   - name: Unarchive a file that is already on the remote machine
     ansible.builtin.unarchive:
       src: /tmp/shipping.zip
       dest: /app
       remote_src: yes

   - name: Install maven
     ansible.builtin.package:
       name: maven
       state: installed
    